export const BUS_ROUTES = [
  {
    id: 1,
    routeNo: "Route A",
    name: "Ramu Town Route",
    color: "#3B82F6",
    capacity: 40,
    fee: "৳800/month",
    departureTime: "7:00 AM",
    returnTime: "3:30 PM",
    stops: [
      { name: "Ramu Bazar", time: "7:00 AM" },
      { name: "Ramu Hospital", time: "7:10 AM" },
      { name: "Khuniapalong Bridge", time: "7:20 AM" },
      { name: "Dhuapalong Bus Stand", time: "7:30 AM" },
      { name: "School Gate", time: "7:45 AM" },
    ],
  },
  {
    id: 2,
    routeNo: "Route B",
    name: "Cox's Bazar Highway",
    color: "#10B981",
    capacity: 50,
    fee: "৳1,200/month",
    departureTime: "6:30 AM",
    returnTime: "3:30 PM",
    stops: [
      { name: "Cox's Bazar City Center", time: "6:30 AM" },
      { name: "Inani Junction", time: "6:50 AM" },
      { name: "Teknaf Road", time: "7:05 AM" },
      { name: "Ramu Crossing", time: "7:25 AM" },
      { name: "School Gate", time: "7:45 AM" },
    ],
  },
  {
    id: 3,
    routeNo: "Route C",
    name: "Ukhia Village Route",
    color: "#F59E0B",
    capacity: 35,
    fee: "৳700/month",
    departureTime: "7:10 AM",
    returnTime: "3:30 PM",
    stops: [
      { name: "Ukhia Bazar", time: "7:10 AM" },
      { name: "Rajapalong", time: "7:20 AM" },
      { name: "Dhuapalong East", time: "7:35 AM" },
      { name: "School Gate", time: "7:45 AM" },
    ],
  },
  {
    id: 4,
    routeNo: "Route D",
    name: "Pekua Direct Route",
    color: "#8B5CF6",
    capacity: 30,
    fee: "৳900/month",
    departureTime: "6:50 AM",
    returnTime: "3:30 PM",
    stops: [
      { name: "Pekua Upazila Gate", time: "6:50 AM" },
      { name: "Pekua Bazar", time: "7:00 AM" },
      { name: "Sonapahar", time: "7:15 AM" },
      { name: "Ramu Road", time: "7:30 AM" },
      { name: "School Gate", time: "7:45 AM" },
    ],
  },
];

export const LIBRARY_BOOKS = [
  { id: 1, title: "Amar Sonar Bangla", author: "Rabindranath Tagore", category: "Literature", status: "available", coverColor: "#EC4899" },
  { id: 2, title: "Padma Nodir Majhi", author: "Manik Bandopadhyay", category: "Fiction", status: "borrowed", coverColor: "#8B5CF6" },
  { id: 3, title: "Science for Class Five", author: "National Curriculum", category: "Science", status: "available", coverColor: "#3B82F6" },
  { id: 4, title: "Gonit Bichitra", author: "Bangla Academy", category: "Math", status: "available", coverColor: "#F59E0B" },
  { id: 5, title: "Bangladesh O Biplob", author: "Mufakkharul Islam", category: "History", status: "borrowed", coverColor: "#EF4444" },
  { id: 6, title: "Chander Pahar", author: "Bibhutibhushan Bandopadhyay", category: "Fiction", status: "available", coverColor: "#10B981" },
  { id: 7, title: "English Grammar Guide", author: "Wren & Martin", category: "English", status: "available", coverColor: "#06B6D4" },
  { id: 8, title: "Amader Biggan", author: "NCERT Bangladesh", category: "Science", status: "borrowed", coverColor: "#7C3AED" },
  { id: 9, title: "Itihaser Golpo", author: "Md. Abdul Quadir", category: "History", status: "available", coverColor: "#DC2626" },
  { id: 10, title: "Sahitya Samagra", author: "Jibanananda Das", category: "Literature", status: "available", coverColor: "#EA580C" },
  { id: 11, title: "Math Practice Book", author: "Dr. Rashid Khan", category: "Math", status: "available", coverColor: "#2563EB" },
  { id: 12, title: "Primary English Reader", author: "National Curriculum", category: "English", status: "borrowed", coverColor: "#059669" },
  { id: 13, title: "Prakritik Bishwa", author: "Dilwar Hossain", category: "Science", status: "available", coverColor: "#D946EF" },
  { id: 14, title: "Bangla Sahityer Itihas", author: "Dwijendralal Ray", category: "Literature", status: "available", coverColor: "#F97316" },
  { id: 15, title: "Ganit Sorokuri", author: "Dr. M. Ahmed", category: "Math", status: "borrowed", coverColor: "#14B8A6" },
  { id: 16, title: "World History for Kids", author: "Sarah Collins", category: "History", status: "available", coverColor: "#6366F1" },
];

export const DONATION_GOALS = [
  {
    id: 1,
    title: "New Computer Lab",
    description: "Setting up a modern computer lab with 30 new workstations and internet connectivity for digital literacy.",
    goal: 1000000,
    raised: 500000,
    donors: 127,
    icon: "Monitor",
  },
  {
    id: 2,
    title: "Playground Renovation",
    description: "Upgrading the playground with proper flooring, new goalposts, basketball hoop, and safety equipment.",
    goal: 500000,
    raised: 350000,
    donors: 89,
    icon: "Trees",
  },
  {
    id: 3,
    title: "Library Books Fund",
    description: "Expanding our library collection with 500+ new books covering science, literature, and children's stories.",
    goal: 300000,
    raised: 180000,
    donors: 64,
    icon: "BookOpen",
  },
  {
    id: 4,
    title: "Scholarship Fund",
    description: "Supporting meritorious students from underprivileged families with full tuition and supplies.",
    goal: 800000,
    raised: 420000,
    donors: 102,
    icon: "GraduationCap",
  },
];

export const RECENT_DONORS = [
  { name: "Anonymous", amount: 10000, date: "2026-06-20" },
  { name: "Kamal Hossain", amount: 5000, date: "2026-06-19" },
  { name: "Anonymous", amount: 25000, date: "2026-06-18" },
  { name: "Fatima Khatun", amount: 2000, date: "2026-06-17" },
  { name: "Anonymous", amount: 15000, date: "2026-06-16" },
  { name: "Rahim Uddin", amount: 3000, date: "2026-06-15" },
  { name: "Anonymous", amount: 8000, date: "2026-06-14" },
  { name: "Sabrina Akter", amount: 7500, date: "2026-06-13" },
];

export const CAMPUS_GALLERY = [
  { id: 1, title: "Main Building", area: "Front Campus", color: "#3B82F6", description: "Our historic main building houses 8 classrooms across two floors with modern facilities." },
  { id: 2, title: "School Library", area: "Ground Floor, Block A", color: "#10B981", description: "A well-stocked library with over 2000 books, magazines, and digital reading materials." },
  { id: 3, title: "Playground", area: "East Campus", color: "#F59E0B", description: "Spacious playground for cricket, football, and other outdoor activities." },
  { id: 4, title: "Computer Lab", area: "First Floor, Block B", color: "#8B5CF6", description: "Modern computer lab with 15 workstations and internet connectivity." },
  { id: 5, title: "Classroom", area: "All Blocks", color: "#EC4899", description: "Smart classrooms equipped with projectors and interactive boards." },
  { id: 6, title: "School Garden", area: "West Campus", color: "#14B8A6", description: "Green garden area with educational plants and a small pond for nature studies." },
  { id: 7, title: "Assembly Hall", area: "Block C", color: "#EF4444", description: "Multi-purpose hall for school assemblies, cultural programs, and parent meetings." },
  { id: 8, title: "Prayer Room", area: "Ground Floor", color: "#06B6D4", description: "Dedicated prayer space for students and staff." },
];

export const TESTIMONIALS = [
  {
    id: 1,
    quote: "My daughter has grown so much in confidence since joining DGPS. The teachers are incredibly caring and the curriculum is well-structured. I couldn't be happier with her progress.",
    parentName: "Rahim Uddin",
    childClass: "Class III",
    rating: 5,
    relation: "Father",
  },
  {
    id: 2,
    quote: "The school's focus on moral values alongside academics is what sets it apart. My son has learned discipline and respect while excelling in his studies.",
    parentName: "Fatima Khatun",
    childClass: "Class V",
    rating: 5,
    relation: "Mother",
  },
  {
    id: 3,
    quote: "Being a working parent, I appreciate the safe environment and attentive teachers. The school regularly updates us on our child's progress through parent meetings.",
    parentName: "Kamal Hossain",
    childClass: "Class II",
    rating: 4,
    relation: "Father",
  },
  {
    id: 4,
    quote: "The digital classrooms have made learning so much more engaging for my children. They actually look forward to going to school every morning!",
    parentName: "Nusrat Jahan",
    childClass: "Class I",
    rating: 5,
    relation: "Mother",
  },
  {
    id: 5,
    quote: "I studied at this very school and now my children are here. The tradition of excellence continues. The teachers truly care about every student's future.",
    parentName: "Abdul Halim",
    childClass: "Class IV",
    rating: 5,
    relation: "Father",
  },
  {
    id: 6,
    quote: "The library and extracurricular activities have helped my child discover a love for reading and art. Thank you DGPS for nurturing holistic development.",
    parentName: "Sabrina Akter",
    childClass: "Class III",
    rating: 4,
    relation: "Mother",
  },
  {
    id: 7,
    quote: "We shifted to Cox's Bazar from Dhaka and were worried about finding a good school. DGPS exceeded all our expectations. The principal is very approachable.",
    parentName: "Tanvir Rahman",
    childClass: "Class V",
    rating: 5,
    relation: "Father",
  },
  {
    id: 8,
    quote: "My twins are in Class II and they love the sports activities here. The teachers are patient and understanding. Highly recommend this school to all parents.",
    parentName: "Roksana Begum",
    childClass: "Class II",
    rating: 5,
    relation: "Mother",
  },
];

export const CALENDAR_EVENTS = [
  { id: 1, title: "School Reopens", date: "2026-01-01", type: "academic", color: "#3B82F6", description: "New academic session begins. All students report by 8:00 AM." },
  { id: 2, title: "Republic Day Observation", date: "2026-01-21", type: "cultural", color: "#EF4444", description: "Special assembly and cultural program to observe Republic Day." },
  { id: 3, title: "Parent-Teacher Meeting", date: "2026-02-14", type: "meeting", color: "#10B981", description: "Scheduled meetings to discuss student progress. Time: 9:00 AM - 12:00 PM." },
  { id: 4, title: "Science Fair", date: "2026-02-28", type: "academic", color: "#F59E0B", description: "Annual science fair showcasing student projects and experiments." },
  { id: 5, title: "Language Day", date: "2026-02-21", type: "cultural", color: "#EC4899", description: "International Mother Language Day observance with poetry recitation and cultural performances." },
  { id: 6, title: "Independence Day", date: "2026-03-26", type: "cultural", color: "#EF4444", description: "National Independence Day celebrations with flag hoisting and cultural program." },
  { id: 7, title: "Mid-Term Exam", date: "2026-04-10", type: "exam", color: "#8B5CF6", description: "Mid-term examinations begin for all classes. Routine available at school office." },
  { id: 8, title: "Mid-Term Exam Ends", date: "2026-04-20", type: "exam", color: "#8B5CF6", description: "Last day of mid-term examinations." },
  { id: 9, title: "Sports Day", date: "2026-05-15", type: "sports", color: "#F97316", description: "Annual sports day with athletics, team games, and prize distribution." },
  { id: 10, title: "Summer Vacation", date: "2026-05-20", type: "holiday", color: "#06B6D4", description: "Summer vacation begins. School reopens on June 1." },
  { id: 11, title: "School Reopens", date: "2026-06-01", type: "academic", color: "#3B82F6", description: "School reopens after summer vacation. New term begins." },
  { id: 12, title: "Book Week", date: "2026-06-15", type: "cultural", color: "#10B981", description: "Week-long book fair and reading activities. Students bring books from home to exchange." },
  { id: 13, title: "PTA Meeting", date: "2026-06-25", type: "meeting", color: "#EC4899", description: "Parent-Teacher Association monthly meeting. All parents welcome." },
  { id: 14, title: "Final Exam", date: "2026-11-15", type: "exam", color: "#8B5CF6", description: "Annual final examinations begin for all classes." },
  { id: 15, title: "Annual Day", date: "2026-12-15", type: "cultural", color: "#F59E0B", description: "Annual day celebrations with prize distribution, cultural performances, and exhibition." },
  { id: 16, title: "Winter Vacation", date: "2026-12-25", type: "holiday", color: "#06B6D4", description: "Winter vacation begins. School reopens on January 1, 2027." },
];
